name: CI & Release

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: galaxyeye88/pulsar-rpa

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Read VERSION
        id: version
        run: |
          echo "VERSION=$(head -n 1 VERSION)" >> $GITHUB_ENV

      - name: Maven build and deploy to local repo
        run: ./mvnw clean install -DskipTests -Pall-modules

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest -f Dockerfile-jar .

      - name: Start Docker container
        run: |
          docker run -d --rm --name pulsar-rpa-test -p 8182:8182 $IMAGE_NAME:$VERSION
          sleep 10  # 等待 Spring Boot 启动

      - name: Run curl integration tests from README.md
        run: |
          ./bin/scrape.sh

      - name: Stop Docker container
        if: always()
        run: docker stop pulsar-rpa-test || true

      - name: Deploy to Sonatype OSSRH
        if: success()
        run: |
          ./mvnw deploy -Pplaton-release -Pplaton-deploy -DskipTests \
            -Dgpg.skip=true \
            -Dossrh.username=${{ secrets.SONATYPE_USERNAME }} \
            -Dossrh.password=${{ secrets.SONATYPE_PASSWORD }}

      - name: Push Docker image
        if: success()
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
